<?php

########################################################################
# Extension Manager/Repository config file for ext: "themes"
#
# Auto generated by Extension Builder 2011-09-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Theme Manager',
	'description' => 'Theme Manager for TYPO3.',
	'category' => 'module',
	'author' => 'Themes-Team (Kay Strobach, Jo Hasenau, Thomas Deuling)',
	'author_email' => 'team@typo3-themes.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'typo3' => '6.1.1-',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
